version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /api/node_modules 
    environment:
      - NODE_ENV=development
    command: npm run dev
    env_file:
      - .env